### ISSUE TITLE
реализовать всякое тривиальное по тз

### ISSUE THREAD

**Issue by marqueewinq** [marqueewinq/adeptus-engine#4]

**Comment by marqueewinq** [comment]
https://docs.google.com/document/d/1jhBljC4yFUNoGnt3N8mysLN0Yw-1HykgpBpdBLme42s/edit

**Comment by marqueewinq** [comment]
Понять:
- [ ] обязанности в команде
- [ ] что происходит с влиянием
- [ ] события
- [ ] координаты
- [x] боёвку

**Comment by Waldesfray** [comment]
Координаты
См карту map.html
Вычисляем координаты как адрес ячейки в таблице. Длина пути для расчета в ресурсах (минимально необходимой промышленности) - как длину гипотенузы из суммы квадратов катетов. Положение корабля на момент хода в случае, если он не достиг финальной точки - видимо, придется аппроксимировать, т к это может быть не всегда строго 45-градусная гипотенуза.

**Comment by Waldesfray** [comment]
Боевка
Если нужна уже сейчас, то пока просто разрешаем в пользу атакующего. Алгоритмы расчета приказов перерисую из блокнота в блок-схемы сегодня.

**Comment by Waldesfray** [comment]
Влияние
С вдиянием возможны следующие изменения (см ТЗ):
- использование
  Влияние не тратится на задачи, а определяет максимальные пределы их выполнения (например, корабль не пройдет большк клеток за ход, чем ограничивает влияние в промышленности)
- делегирование 
  Можно поделиться частью своего влияния с другим игроком  (игроками), и забрать назад. Это действие можно выполнять сколько угодно раз за ход, но то, что остается у игроков на момент конца хода - используется для всех расчетов.
  Т.е. можно обмануть, и забрать делегированное в последний момент.

**Comment by Waldesfray** [comment]
ВАЖНО
С серверной стороны,  нужно бы сделать возможность выставлять значение личного влияния персонажа (менять его). Доя игротехнических целей.

**Comment by marqueewinq** [comment]
@Waldesfray 

> Положение корабля на момент хода в случае, если он не достиг финальной точки - видимо, придется аппроксимировать, т к это может быть не всегда строго 45-градусная гипотенуза.

Поясни, пожалуйста
